### ISSUE TITLE
App isn't in the nextcloud app store

### ISSUE THREAD

**Issue by Retnuh66** [HyperionApps/Music#12]
Even though this app says it's for nextcloud, I can only find it in the owncloud store. I would really like to be able to play FLAC files from my nextcloud installation =[

**Comment by MrEvertide** [comment]
Hello,

I'm sorry but this app is no longer supported and was left in a development stage.

Also it was not published on either Owncloud or Nextcloud App store. 

It does not support FLAC files and I warn you, Do not use this app in a production environment as it is untested and not completed.
